# Generated by Django 5.0.4 on 2024-05-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_views_counter_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='views_counter',
            new_name='viewed',
        ),
    ]
