# Generated by Django 4.2.2 on 2024-05-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_edit_category', 'Edit Category'), ('can_edit_description', 'Edit Description'), ('can_edit_is_active', 'Edit Is Active')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
